// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: empresas.proto

public final class EmpresasProtos {
  private EmpresasProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmpresaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empresa)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string nome = 2;</code>
     */
    boolean hasNome();
    /**
     * <code>required string nome = 2;</code>
     */
    java.lang.String getNome();
    /**
     * <code>required string nome = 2;</code>
     */
    com.google.protobuf.ByteString
        getNomeBytes();
  }
  /**
   * Protobuf type {@code Empresa}
   */
  public  static final class Empresa extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empresa)
      EmpresaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empresa.newBuilder() to construct.
    private Empresa(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empresa() {
      nome_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empresa(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              nome_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmpresasProtos.internal_static_Empresa_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmpresasProtos.internal_static_Empresa_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EmpresasProtos.Empresa.class, EmpresasProtos.Empresa.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NOME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nome_;
    /**
     * <code>required string nome = 2;</code>
     */
    public boolean hasNome() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string nome = 2;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nome_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nome = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNome()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nome_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nome_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EmpresasProtos.Empresa)) {
        return super.equals(obj);
      }
      EmpresasProtos.Empresa other = (EmpresasProtos.Empresa) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasNome() == other.hasNome());
      if (hasNome()) {
        result = result && getNome()
            .equals(other.getNome());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasNome()) {
        hash = (37 * hash) + NOME_FIELD_NUMBER;
        hash = (53 * hash) + getNome().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmpresasProtos.Empresa parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmpresasProtos.Empresa parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmpresasProtos.Empresa parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmpresasProtos.Empresa parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmpresasProtos.Empresa parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmpresasProtos.Empresa parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmpresasProtos.Empresa parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmpresasProtos.Empresa parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmpresasProtos.Empresa parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EmpresasProtos.Empresa parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmpresasProtos.Empresa parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmpresasProtos.Empresa parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmpresasProtos.Empresa prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empresa}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empresa)
        EmpresasProtos.EmpresaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EmpresasProtos.internal_static_Empresa_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EmpresasProtos.internal_static_Empresa_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EmpresasProtos.Empresa.class, EmpresasProtos.Empresa.Builder.class);
      }

      // Construct using EmpresasProtos.Empresa.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        nome_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EmpresasProtos.internal_static_Empresa_descriptor;
      }

      @java.lang.Override
      public EmpresasProtos.Empresa getDefaultInstanceForType() {
        return EmpresasProtos.Empresa.getDefaultInstance();
      }

      @java.lang.Override
      public EmpresasProtos.Empresa build() {
        EmpresasProtos.Empresa result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EmpresasProtos.Empresa buildPartial() {
        EmpresasProtos.Empresa result = new EmpresasProtos.Empresa(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nome_ = nome_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmpresasProtos.Empresa) {
          return mergeFrom((EmpresasProtos.Empresa)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmpresasProtos.Empresa other) {
        if (other == EmpresasProtos.Empresa.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasNome()) {
          bitField0_ |= 0x00000002;
          nome_ = other.nome_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasNome()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EmpresasProtos.Empresa parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EmpresasProtos.Empresa) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>required string nome = 2;</code>
       */
      public boolean hasNome() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string nome = 2;</code>
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nome_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nome = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nome = 2;</code>
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nome = 2;</code>
       */
      public Builder clearNome() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>required string nome = 2;</code>
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nome_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empresa)
    }

    // @@protoc_insertion_point(class_scope:Empresa)
    private static final EmpresasProtos.Empresa DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmpresasProtos.Empresa();
    }

    public static EmpresasProtos.Empresa getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Empresa>
        PARSER = new com.google.protobuf.AbstractParser<Empresa>() {
      @java.lang.Override
      public Empresa parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empresa(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empresa> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empresa> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EmpresasProtos.Empresa getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmpresasRepOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EmpresasRep)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Empresa empresa = 1;</code>
     */
    java.util.List<EmpresasProtos.Empresa> 
        getEmpresaList();
    /**
     * <code>repeated .Empresa empresa = 1;</code>
     */
    EmpresasProtos.Empresa getEmpresa(int index);
    /**
     * <code>repeated .Empresa empresa = 1;</code>
     */
    int getEmpresaCount();
    /**
     * <code>repeated .Empresa empresa = 1;</code>
     */
    java.util.List<? extends EmpresasProtos.EmpresaOrBuilder> 
        getEmpresaOrBuilderList();
    /**
     * <code>repeated .Empresa empresa = 1;</code>
     */
    EmpresasProtos.EmpresaOrBuilder getEmpresaOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code EmpresasRep}
   */
  public  static final class EmpresasRep extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EmpresasRep)
      EmpresasRepOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmpresasRep.newBuilder() to construct.
    private EmpresasRep(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmpresasRep() {
      empresa_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmpresasRep(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                empresa_ = new java.util.ArrayList<EmpresasProtos.Empresa>();
                mutable_bitField0_ |= 0x00000001;
              }
              empresa_.add(
                  input.readMessage(EmpresasProtos.Empresa.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          empresa_ = java.util.Collections.unmodifiableList(empresa_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmpresasProtos.internal_static_EmpresasRep_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmpresasProtos.internal_static_EmpresasRep_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EmpresasProtos.EmpresasRep.class, EmpresasProtos.EmpresasRep.Builder.class);
    }

    public static final int EMPRESA_FIELD_NUMBER = 1;
    private java.util.List<EmpresasProtos.Empresa> empresa_;
    /**
     * <code>repeated .Empresa empresa = 1;</code>
     */
    public java.util.List<EmpresasProtos.Empresa> getEmpresaList() {
      return empresa_;
    }
    /**
     * <code>repeated .Empresa empresa = 1;</code>
     */
    public java.util.List<? extends EmpresasProtos.EmpresaOrBuilder> 
        getEmpresaOrBuilderList() {
      return empresa_;
    }
    /**
     * <code>repeated .Empresa empresa = 1;</code>
     */
    public int getEmpresaCount() {
      return empresa_.size();
    }
    /**
     * <code>repeated .Empresa empresa = 1;</code>
     */
    public EmpresasProtos.Empresa getEmpresa(int index) {
      return empresa_.get(index);
    }
    /**
     * <code>repeated .Empresa empresa = 1;</code>
     */
    public EmpresasProtos.EmpresaOrBuilder getEmpresaOrBuilder(
        int index) {
      return empresa_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getEmpresaCount(); i++) {
        if (!getEmpresa(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < empresa_.size(); i++) {
        output.writeMessage(1, empresa_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < empresa_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, empresa_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EmpresasProtos.EmpresasRep)) {
        return super.equals(obj);
      }
      EmpresasProtos.EmpresasRep other = (EmpresasProtos.EmpresasRep) obj;

      boolean result = true;
      result = result && getEmpresaList()
          .equals(other.getEmpresaList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEmpresaCount() > 0) {
        hash = (37 * hash) + EMPRESA_FIELD_NUMBER;
        hash = (53 * hash) + getEmpresaList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmpresasProtos.EmpresasRep parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmpresasProtos.EmpresasRep parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmpresasProtos.EmpresasRep parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmpresasProtos.EmpresasRep parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmpresasProtos.EmpresasRep parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmpresasProtos.EmpresasRep parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmpresasProtos.EmpresasRep parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmpresasProtos.EmpresasRep parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmpresasProtos.EmpresasRep parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EmpresasProtos.EmpresasRep parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmpresasProtos.EmpresasRep parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmpresasProtos.EmpresasRep parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmpresasProtos.EmpresasRep prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EmpresasRep}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EmpresasRep)
        EmpresasProtos.EmpresasRepOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EmpresasProtos.internal_static_EmpresasRep_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EmpresasProtos.internal_static_EmpresasRep_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EmpresasProtos.EmpresasRep.class, EmpresasProtos.EmpresasRep.Builder.class);
      }

      // Construct using EmpresasProtos.EmpresasRep.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEmpresaFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (empresaBuilder_ == null) {
          empresa_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          empresaBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EmpresasProtos.internal_static_EmpresasRep_descriptor;
      }

      @java.lang.Override
      public EmpresasProtos.EmpresasRep getDefaultInstanceForType() {
        return EmpresasProtos.EmpresasRep.getDefaultInstance();
      }

      @java.lang.Override
      public EmpresasProtos.EmpresasRep build() {
        EmpresasProtos.EmpresasRep result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EmpresasProtos.EmpresasRep buildPartial() {
        EmpresasProtos.EmpresasRep result = new EmpresasProtos.EmpresasRep(this);
        int from_bitField0_ = bitField0_;
        if (empresaBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            empresa_ = java.util.Collections.unmodifiableList(empresa_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.empresa_ = empresa_;
        } else {
          result.empresa_ = empresaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmpresasProtos.EmpresasRep) {
          return mergeFrom((EmpresasProtos.EmpresasRep)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmpresasProtos.EmpresasRep other) {
        if (other == EmpresasProtos.EmpresasRep.getDefaultInstance()) return this;
        if (empresaBuilder_ == null) {
          if (!other.empresa_.isEmpty()) {
            if (empresa_.isEmpty()) {
              empresa_ = other.empresa_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEmpresaIsMutable();
              empresa_.addAll(other.empresa_);
            }
            onChanged();
          }
        } else {
          if (!other.empresa_.isEmpty()) {
            if (empresaBuilder_.isEmpty()) {
              empresaBuilder_.dispose();
              empresaBuilder_ = null;
              empresa_ = other.empresa_;
              bitField0_ = (bitField0_ & ~0x00000001);
              empresaBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEmpresaFieldBuilder() : null;
            } else {
              empresaBuilder_.addAllMessages(other.empresa_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getEmpresaCount(); i++) {
          if (!getEmpresa(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EmpresasProtos.EmpresasRep parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EmpresasProtos.EmpresasRep) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<EmpresasProtos.Empresa> empresa_ =
        java.util.Collections.emptyList();
      private void ensureEmpresaIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          empresa_ = new java.util.ArrayList<EmpresasProtos.Empresa>(empresa_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          EmpresasProtos.Empresa, EmpresasProtos.Empresa.Builder, EmpresasProtos.EmpresaOrBuilder> empresaBuilder_;

      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public java.util.List<EmpresasProtos.Empresa> getEmpresaList() {
        if (empresaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(empresa_);
        } else {
          return empresaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public int getEmpresaCount() {
        if (empresaBuilder_ == null) {
          return empresa_.size();
        } else {
          return empresaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public EmpresasProtos.Empresa getEmpresa(int index) {
        if (empresaBuilder_ == null) {
          return empresa_.get(index);
        } else {
          return empresaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public Builder setEmpresa(
          int index, EmpresasProtos.Empresa value) {
        if (empresaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmpresaIsMutable();
          empresa_.set(index, value);
          onChanged();
        } else {
          empresaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public Builder setEmpresa(
          int index, EmpresasProtos.Empresa.Builder builderForValue) {
        if (empresaBuilder_ == null) {
          ensureEmpresaIsMutable();
          empresa_.set(index, builderForValue.build());
          onChanged();
        } else {
          empresaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public Builder addEmpresa(EmpresasProtos.Empresa value) {
        if (empresaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmpresaIsMutable();
          empresa_.add(value);
          onChanged();
        } else {
          empresaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public Builder addEmpresa(
          int index, EmpresasProtos.Empresa value) {
        if (empresaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmpresaIsMutable();
          empresa_.add(index, value);
          onChanged();
        } else {
          empresaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public Builder addEmpresa(
          EmpresasProtos.Empresa.Builder builderForValue) {
        if (empresaBuilder_ == null) {
          ensureEmpresaIsMutable();
          empresa_.add(builderForValue.build());
          onChanged();
        } else {
          empresaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public Builder addEmpresa(
          int index, EmpresasProtos.Empresa.Builder builderForValue) {
        if (empresaBuilder_ == null) {
          ensureEmpresaIsMutable();
          empresa_.add(index, builderForValue.build());
          onChanged();
        } else {
          empresaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public Builder addAllEmpresa(
          java.lang.Iterable<? extends EmpresasProtos.Empresa> values) {
        if (empresaBuilder_ == null) {
          ensureEmpresaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, empresa_);
          onChanged();
        } else {
          empresaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public Builder clearEmpresa() {
        if (empresaBuilder_ == null) {
          empresa_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          empresaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public Builder removeEmpresa(int index) {
        if (empresaBuilder_ == null) {
          ensureEmpresaIsMutable();
          empresa_.remove(index);
          onChanged();
        } else {
          empresaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public EmpresasProtos.Empresa.Builder getEmpresaBuilder(
          int index) {
        return getEmpresaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public EmpresasProtos.EmpresaOrBuilder getEmpresaOrBuilder(
          int index) {
        if (empresaBuilder_ == null) {
          return empresa_.get(index);  } else {
          return empresaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public java.util.List<? extends EmpresasProtos.EmpresaOrBuilder> 
           getEmpresaOrBuilderList() {
        if (empresaBuilder_ != null) {
          return empresaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(empresa_);
        }
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public EmpresasProtos.Empresa.Builder addEmpresaBuilder() {
        return getEmpresaFieldBuilder().addBuilder(
            EmpresasProtos.Empresa.getDefaultInstance());
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public EmpresasProtos.Empresa.Builder addEmpresaBuilder(
          int index) {
        return getEmpresaFieldBuilder().addBuilder(
            index, EmpresasProtos.Empresa.getDefaultInstance());
      }
      /**
       * <code>repeated .Empresa empresa = 1;</code>
       */
      public java.util.List<EmpresasProtos.Empresa.Builder> 
           getEmpresaBuilderList() {
        return getEmpresaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          EmpresasProtos.Empresa, EmpresasProtos.Empresa.Builder, EmpresasProtos.EmpresaOrBuilder> 
          getEmpresaFieldBuilder() {
        if (empresaBuilder_ == null) {
          empresaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              EmpresasProtos.Empresa, EmpresasProtos.Empresa.Builder, EmpresasProtos.EmpresaOrBuilder>(
                  empresa_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          empresa_ = null;
        }
        return empresaBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EmpresasRep)
    }

    // @@protoc_insertion_point(class_scope:EmpresasRep)
    private static final EmpresasProtos.EmpresasRep DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmpresasProtos.EmpresasRep();
    }

    public static EmpresasProtos.EmpresasRep getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EmpresasRep>
        PARSER = new com.google.protobuf.AbstractParser<EmpresasRep>() {
      @java.lang.Override
      public EmpresasRep parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmpresasRep(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmpresasRep> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmpresasRep> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EmpresasProtos.EmpresasRep getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empresa_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empresa_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmpresasRep_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmpresasRep_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016empresas.proto\"#\n\007Empresa\022\n\n\002id\030\001 \002(\005\022" +
      "\014\n\004nome\030\002 \002(\t\"(\n\013EmpresasRep\022\031\n\007empresa\030" +
      "\001 \003(\0132\010.EmpresaB\020B\016EmpresasProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Empresa_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empresa_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empresa_descriptor,
        new java.lang.String[] { "Id", "Nome", });
    internal_static_EmpresasRep_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmpresasRep_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmpresasRep_descriptor,
        new java.lang.String[] { "Empresa", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
